sudo: false
matrix:
  include:
    - rvm: 2.4.1
      language: ruby
      env:
        - RAILS_ENV=test
      cache:
        bundler: true
      services:
        - redis-server
        - mysql
      script:
        - ruby --version
        - gem install rapidfire
    - rvm: 2.4.1
      language: ruby
      env:
        - RAILS_ENV=test
      cache:
        bundler: true
      services:
        - redis-server
        - mysql
      script:
        - ruby --version
addons:
  hosts:
    - db
    - cache
