matrix:
  include:
    - rvm: 2.4.1
      language: ruby
      env:
        - RAILS_ENV=test
        - "SPEC_GROUP=1,2"
      cache:
        bundler: true
      services:
        - redis-server
        - mysql
      script:
        - ruby --version
    - rvm: 2.4.1
      language: ruby
      env:
        - RAILS_ENV=test
        - "SPEC_GROUP=1,2"
      cache:
        bundler: true
      services:
        - redis-server
        - mysql
      script:
        - ruby --version
addons:
  hosts:
    - db
    - cache
